### ISSUE TITLE
[WEBSITE] Change the HTTP to HTTPS

### ISSUE THREAD

**Issue by Neustradamus** [WinMerge/winmerge-v2#107]
Can you change the http to https for the website?

**Comment by gerundt** [comment]
Currently not. We only have FTP access. Only the project founder has access to the settings.

And unfortunately we can not reach him at the moment. :-(

**Comment by Neustradamus** [comment]
@gerundt: Any news?

**Comment by gerundt** [comment]
Still no contact to the project founder @grimmdp :(

The only way would be to buy a new internet domain. But nothing would be good like winmerge.org

**Comment by MailYouLater** [comment]
To get a cert you can use [Let's Encrypt](https://letsencrypt.org/) with a [manual http challenge](https://certbot.eff.org/docs/using.html#manual), which is really easy with [Greenlock](https://greenlock.domains/) which just requires the domain name, email address, upload the challenge file, then once their server has been able to download the challenge file from the specified location, you'll be issued a cert.  I'm not sure about actually getting the server to serve https though, since when I try to connect to https://winmerge.org or https://www.winmerge.org right now my browser tells me ERR_SSL_PROTOCOL_ERROR, and I can't seem to find any more information as to what specifically that means.

**Comment by gerundt** [comment]
Our main problem is, that we have currently no access to the website 
config. We have only a FTP login to update the content. Only Dean, the 
project founder, have access to the config. But we have no contact for 
months. 🙈

**Comment by MailYouLater** [comment]
Do you not have his contact info?

**Comment by MailYouLater** [comment]
According to [Domain Tools](http://whois.domaintools.com/winmerge.org) the registrar is dotEarth.com, but [their whois system](https://www.dotearth.com/cgi-bin/www.dotearth.com/verify-whois.cgi) reveals no useful contact info. According to [NetCraft](https://toolbar.netcraft.com/site_report?url=http://winmerge.org) the registrar is pir.org, and [their whois system](https://pir.org/products/org-domain/#domain_form) isn't any more forthcoming, except that their page also says (just above the whois lookup form) "If you believe you have a legitimate interest in accessing non-public WHOIS data please submit your request to WHOISrequest@pir.org." 

So, perhaps you could send an email to that address stating that you help Dean manage the WinMerge website, but haven't been able to contact him regarding some important updates, and hopefully they'll provide you the contact information they're required to have on file.

**Comment by gerundt** [comment]
I sended @grimmdp a mail today. We will see. Maybe this times it works.

**Comment by MailYouLater** [comment]
Well that's interesting. ... I'm guessing you got through to him, but I'm a little concerned with the new configuration too.
Previously http versions of both winmerge.org and www.winmerge.org worked, and https versions of both didn't serve any content due to errors.  Now, both http and https versions of winmerge.org work, and both http and https versions of www.winmerge.org redirect to the http version of winmerge.org.

This is an improvement in functionality, since now https://winmerge.org is working, but now you have a basic user trust issue, in that anyone who goes to https://www.winmerge.org is _expecting_ to be on a secure connection, but is being silently redirected to an insecure connection at http://winmerge.org.  Can you possibly see about rectifying this too, so that people visiting the secure https://www.winmerge.org would be redirected to the secure https://winmerge.org instead.

Thank you for looking into this.

**Comment by gerundt** [comment]
Maybe Dean or I had SPAM problems in the past? Currently the mails works without problems!

I updated the `.htaccess` file and some other parts and hopefully the Redirects works now:
https://bitbucket.org/winmerge/website/commits/d334ed1470883d2cf3aa702fc2bd3b0ad50e5cfa

**Comment by MailYouLater** [comment]
Awesome. Now http://winmerge.org, http://www.winmerge.org, and https://www.winmerge.org forward to https://winmerge.org, which works, and [gets an "A" rating on SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=winmerge.org).

I think this issue can be closed. 😄

**Comment by Neustradamus** [comment]
@MailYouLater, @gerundt: Nice :)

**Comment by Neustradamus** [comment]
Thanks @sdottaka for link updates! :)

@gerundt: Have you rights now on the domain or always only @grimmdp?

**Comment by gerundt** [comment]
Hi @Neustradamus, only @grimmdp has access to the domain. This are things, you can only change on the website from the hoster. And normally you have then also access to banking data and other stuff. I can understand that Dean want this keep private. ;-)
